name: NPM Service API
description: |
  This workflow automates the process of pushing the service-api package to the NPM registry.
run-name: |
  ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸ’¡ Checking out the ${{ github.repository }} repository"
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "ğŸ’¡ Installing Node.js v16 on the runner"
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the desired Node.js version
          cache: 'npm' # Cache NPM dependencies

      - run: echo "ğŸ’¡ Installing dependencies for ${{ github.repository }}"
      - name: Install dependencies
        run: npm install

      # - run: "ğŸ’¡ Running tests for ${{ github.repository }}"
      # - name: Run tests
      #   run: npm test

      - run: echo "ğŸ’¡ Publishing ${{ github.repository }} to the NPM registry"
      - name: Publish to NPM
        run: npm publish --registry https://npm.pkg.github.com/${{ github.repository_owner }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "ğŸ This job's status is ${{ job.status }}."